config/routes.rb
Rails.application.routes.draw do
  get 'pages/secret'

	resources :credit_cards

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Add a root route if you don't have one...
	# We can use users#new for now, or replace this with the controller and action you want to be the site root:
	root to: 'users#new'

	get 'users/show' => 'users#show'

  	# sign up page with form:
	get 'users/new' => 'users#new', as: :new_user

	# create (post) action for when sign up form is submitted:
	post 'users' => 'users#create'

	# log in page with form:
	get '/login'     => 'sessions#new'

	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'

	# delete action to log out:
	delete '/logout' => 'sessions#destroy'

  # new transaction:
	get 'transactions/new'  => 'transactions#new'

	post 'transactions/new' => 'transactions#new'

	# create (post) transaction:
	post 'transactions/'    => 'transactions#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinFriend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>

    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

<body class="container">
  <nav class="container">
    <div class="nav-wrapper">
        <% if current_user %>
        <a href="/users/show" class="brand-logo left"> <i class="material-icons">card_membership</i>FinFriend</a>
          <ul id="nav-mobile" class="right">
            <!-- current_user will return true if a user is logged in -->
            <li><i class="material-icons prefix">account_circle</i></li>
            <li><%= link_to("#{current_user.name}", "/users/show")%>|</li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
        <% else %>
          <!-- not logged in -->
          <a href="/users/new" class="brand-logo"><i class="material-icons">card_membership</i>FinFriend</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><%= link_to 'Log In', login_path %> or <%= link_to 'Register', new_user_path %></li>
          </ul>
        <% end %>
    </div>
  </nav>
  <div class="container">
    <% if notice %>
      <%= notice %>
  	<% end %>

  	<% if alert %>
      <%= alert %>
  	<% end %>
    <%= yield %>
  </div>
  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="js/materialize.min.js"></script>
  </body>
</html>